/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.portalez.web.tramite.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.portalez.web.tramite.model.Tramite;
import com.portalez.web.tramite.service.TramiteLocalServiceUtil;

/**
 * The extended model base implementation for the Tramite service. Represents a row in the &quot;slnc_Tramite&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TramiteImpl}.
 * </p>
 *
 * @author Jorge Loayza-Soloisolo
 * @see TramiteImpl
 * @see com.portalez.web.tramite.model.Tramite
 * @generated
 */
public abstract class TramiteBaseImpl extends TramiteModelImpl
	implements Tramite {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tramite model instance should use the {@link Tramite} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			TramiteLocalServiceUtil.addTramite(this);
		}
		else {
			TramiteLocalServiceUtil.updateTramite(this);
		}
	}
}